// Proxy Auto-Config file generated by autoproxy2pac, 2014-02-07 21:41:48
function FindProxyForURL(url, host) {
    var autoproxy = 'PROXY 127.0.0.1:8087';
    var blackhole = 'PROXY 127.0.0.1:8086';
    var defaultproxy = 'DIRECT';

    if (dnsDomainIs(host, '.4399.com')
    {
        return autoproxy;
    }
    
}

